name: Publish Extension
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/main.yaml"

env:
  API_URL: https://api.samepage.network
  AWS_ACCESS_KEY_ID: ${{ secrets.SAMEPAGE_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SAMEPAGE_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  ROAMJS_DEVELOPER_TOKEN: ${{ secrets.ROAMJS_DEVELOPER_TOKEN }}
  ROAMJS_EMAIL: support@roamjs.com
  ROAMJS_EXTENSION_ID: samepage
  ROAMJS_RELEASE_TOKEN: ${{ secrets.ROAMJS_RELEASE_TOKEN }}
  WEB_SOCKET_URL: wss://ws.samepage.network

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npx roamjs-scripts build --labs
      - name: publish (SamePage)
        run: npx samepage publish --domain samepage.network/extensions --path roam
      # instead of publishing in two places, figure out
      # a way to point the RoamJS link to SamePage
      # - name: publish (RoamJS)
      #   run: npx roamjs-scripts publish --labs
