name: Publish Extension
on:
  push:
    branches: main
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/main.yaml"

env:
  API_URL: https://lambda.roamjs.com
  ROAMJS_DEVELOPER_TOKEN: ${{ secrets.ROAMJS_DEVELOPER_TOKEN }}
  ROAMJS_EMAIL: support@roamjs.com
  ROAMJS_EXTENSION_ID: multiplayer
  ROAMJS_RELEASE_TOKEN: ${{ secrets.ROAMJS_RELEASE_TOKEN }}
  WEB_SOCKET_URL: ${{ secrets.WEB_SOCKET_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npx roamjs-scripts build
      - name: publish
        run: npx roamjs-scripts publish --path $ROAMJS_EXTENSION_ID --nocache
