name: Test Extension
on:
  push:
    branches: main
    paths:
      - "tests/**"
      - ".github/workflows/tests.yaml"

env:
  ROAM_USERNAME: test@samepage.network
  ROAM_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
  API_URL: https://api.samepage.network
  WEB_SOCKET_URL: wss://ws.samepage.network

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: install playwright
        run: npx playwright install
      - name: test
        run: npm t
      - name: ls
        if: always()
        run: |
          ls
          ls playwright-report
